
server:
  port: 8010
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.52.199:3306/sass?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis-plus:
  config-location: classpath:mybatis-config.xml
logging:
  config: classpath:log4j2-spring.xml