server:
  port: 8082
spring:
#  mybatis 查询date类型数据时设置时区
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.52.193:3306/sync_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      max-lifetime: 180000

mybatis-plus:
  config-location: classpath:mybatis-config.xml
logging:
  config: classpath:log4j2-spring.xml
